import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/userprofileprojects">UserprofileProjects</Link>
        </li>
        <li>
          <Link to="/userprofileactivity">UserprofileActivity</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/signup">Signup</Link>
        </li>
        <li>
          <Link to="/dashb">DashB</Link>
        </li>
        <li>
          <Link to="/xone">XOne</Link>
        </li>
        <li>
          <Link to="/x">X</Link>
        </li>
        <li>
          <Link to="/backlog">Backlog</Link>
        </li>
        <li>
          <Link to="/boardsprofileascrollable">BoardsProfileAScrollable</Link>
        </li>
        <li>
          <Link to="/profilesectionoptb">ProfileSectionOptB</Link>
        </li>
        <li>
          <Link to="/backlogone">BacklogOne</Link>
        </li>
        <li>
          <Link to="/teamsprofilea">TeamsProfileA</Link>
        </li>
        <li>
          <Link to="/personalinformation">PersonalInformation</Link>
        </li>
        <li>
          <Link to="/personalinformationtwo">PersonalInformationTwo</Link>
        </li>
        <li>
          <Link to="/personalinformationone">PersonalInformationOne</Link>
        </li>
        <li>
          <Link to="/desktopone">DesktopOne</Link>
        </li>
        <li>
          <Link to="/desktoptwo">DesktopTwo</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
